#!/bin/bash

dir=$1

if [ "$#" -lt "1" ]; then
	echo "Usage: ./c_project [project_name] Optional: [filename(s)]"
	exit 0
fi

if [ -d ./$dir ]; then
	echo "$dir already exist in current folder."
	exit 0
fi

mkdir ./$dir
touch ./$dir/Makefile
echo -n "
CC=gcc
FLAGS=-Wall -Werror -g -fsanitize=address
LDFLAGS = -lm
OBJS=">./$dir/Makefile
echo "we have $# arguments"
if [ "$#" -gt 1 ]; then
	for((i=2; i<=$#; i++)); do
		echo -n "${!i}.o ">>./$dir/Makefile;
	done
else
	echo "main.o">>./$dir/Makefile;
fi
echo "
TARGET=main
MAIN_SOURCE=main.c

all: \$(TARGET)

\$(TARGET): \$(OBJS)
	\$(CC) \$(FLAGS) $^ -o \$@ \$(LDFLAGS)

.PHONY:
build: \$(OBJS)
	\$(CC) \$(FLAGS) $^ -o \$@ \$(LDFLAGS)

%.o: %.c
	\$(CC) -c \$(FLAGS) $< -o \$@

.PHONY:
clean:
	rm -f \$(OBJS)
	rm -f \$(TARGET)
	rm -rf *.out
">>./$dir/Makefile

for ((i=2; i<=$#; i++));do
	newc_file ./$dir/"${!i}";
done

echo "$dir is created."
ls -al | grep $dir

