#!/bin/bash

file=$1

if [ "$#" -lt "1" ]; then
	echo "Usage: newc_file [filename] [optional: function_name]"
	exit 0
fi

if [ -f ./$file ]; then
  echo "File already exist."
  exit 0
fi

func_name="main"
if [ "$#" -gt 1 ]; then
	func_name=$2
fi

echo "#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int $func_name(int argc, char** argv)
{
	return 0;
}" > $file.c
echo "$file.c is created"
