#!/bin/bash

dir=$1

if [ "$#" -lt "1" ]; then
	echo "Usage: ./c_project [project_name] Optional: [filename(s)]"
	exit 0
fi

if [ -d ./$dir ] && [ "$dir" != "." ]; then
	echo "$dir already exist in current folder."
	exit 0
fi

targetname=$dir
if [ "$targetname" == "." ]; then
	targetname="${PWD##*/}"
	if [ -f ./$targetname ]; then
		echo "Please specify a targetname for the project"
		exit 0
	fi
fi

mkdir ./$dir
touch ./$dir/Makefile
echo -n "
CC=gcc
FLAGS=-Wall -Werror -g -fsanitize=address
LDFLAGS = -lm
OBJS=">./$dir/Makefile

if [ "$#" -gt 1 ]; then
	for((i=2; i<=$#; i++)); do
		echo -n "${!i}.o ">>./$dir/Makefile;
	done
fi

echo -n "main.o
TARGET=$targetname
MAIN_SOURCE=">>./$dir/Makefile;

if [ "$#" -gt 1 ]; then
	for((i=2; i<=$#; i++)); do
		echo -n "${!i}.c ">>./$dir/Makefile
	done
fi

echo "main.c
all: \$(TARGET)

\$(TARGET): \$(OBJS)
	\$(CC) \$(FLAGS) $^ -o \$@ \$(LDFLAGS)

.PHONY:
build: \$(OBJS)
	\$(CC) \$(FLAGS) $^ -o \$@ \$(LDFLAGS)

%.o: %.c
	\$(CC) -c \$(FLAGS) $< -o \$@

.PHONY:
clean:
	rm -f \$(OBJS)
	rm -f \$(TARGET)
	rm -rf *.out
">>./$dir/Makefile

for ((i=2; i<=$#; i++));do
	newc_file ./$dir/"${!i}" ${!i}
done
newc_file ./$dir/main

echo "$dir is created."
ls -al | grep $dir

